# Generated by Django 2.0 on 2017-12-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], default='R', max_length=1),
        ),
    ]
